# Generated by Django 6.0.6 on 2026-07-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaytimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_minutes', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_forever_minutes', models.PositiveIntegerField(default=0)),
                ('playtime_recent_minutes', models.PositiveIntegerField(default=0)),
                ('playtime_windows_minutes', models.PositiveIntegerField(default=0)),
                ('playtime_mac_minutes', models.PositiveIntegerField(default=0)),
                ('playtime_linux_minutes', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-playtime_forever_minutes', 'game__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='achievement',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='locked_icon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('game', 'api_name'), name='unique_game_achievement'),
        ),
        migrations.AddField(
            model_name='playerachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='games.achievement'),
        ),
        migrations.AddField(
            model_name='playerachievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progress', to='players.player'),
        ),
        migrations.AddField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='games.game'),
        ),
        migrations.AddField(
            model_name='usergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to='players.player'),
        ),
        migrations.AddField(
            model_name='playtimesnapshot',
            name='user_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='games.usergame'),
        ),
        migrations.AddIndex(
            model_name='playerachievement',
            index=models.Index(fields=['player', 'achieved'], name='games_playe_player__81d51d_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerachievement',
            constraint=models.UniqueConstraint(fields=('player', 'achievement'), name='unique_player_achievement'),
        ),
        migrations.AddIndex(
            model_name='usergame',
            index=models.Index(fields=['player', '-playtime_forever_minutes'], name='games_userg_player__06e5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='usergame',
            index=models.Index(fields=['player', '-last_played_at'], name='games_userg_player__c8cbe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='usergame',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='unique_player_game'),
        ),
        migrations.AddIndex(
            model_name='playtimesnapshot',
            index=models.Index(fields=['user_game', 'recorded_at'], name='games_playt_user_ga_408479_idx'),
        ),
    ]
